/*
  Copyright 2010, UCAR/Unidata
  See COPYRIGHT file for copying and redistribution conditions.

  This program writes a data file from the CAM model run. (Thanks to
  Jim Edwards for contributing this example file.)

  This code originally generated by ncgen.

  $Id: tst_camrun.c,v 1.2 2010/05/20 13:17:50 ed Exp $
*/
#include <config.h>
#include <nc_tests.h>
#include "err_macros.h"
#include <stdio.h>
#include <stdlib.h>
#include <netcdf.h>
#include <unistd.h>

#define FILE_NAME "tst_camrun.nc"
   /* rank (number of dimensions) for each variable */
#   define RANK_P0 0

int
main()
{
   int  ncid;  /* netCDF id */

   /* dimension ids */
   int lat_dim;
   int lon_dim;

   /* dimension lengths */
   size_t lat_len = 96;
   size_t lon_len = 144;

   /* variable ids */
   int P0_id;

   /* enter define mode */
   if (nc_create(FILE_NAME, NC_NETCDF4, &ncid)) ERR;

   /* define dimensions */
   if (nc_def_dim(ncid, "lat", lat_len, &lat_dim)) ERR;
   if (nc_def_dim(ncid, "lon", lon_len, &lon_dim)) ERR;

   /* define variables */

   if (nc_def_var(ncid, "P0", NC_DOUBLE, RANK_P0, 0, &P0_id)) ERR;

   /* leave define mode */
   if (nc_enddef (ncid)) ERR;
   //
   // /* assign variable data */
   if (nc_close(ncid)) ERR;

   SUMMARIZE_ERR;
   FINAL_RESULTS;
}
